# Generated by Django 4.0.4 on 2024-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_url',
            field=models.URLField(max_length=500),
        ),
    ]
