# Generated by Django 4.0.4 on 2024-06-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_alter_borrowing_book_alter_borrowing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
