# Generated by Django 4.0.4 on 2024-06-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_alter_borrowing_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='expected_return_date',
            field=models.DateField(),
        ),
    ]
