# Generated by Django 4.0.4 on 2024-06-13 18:32

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0005_alter_borrowing_expected_return_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(check=models.Q(('expected_return_date__gte', django.db.models.expressions.F('borrow_date'))), name='expected_return_date_gte_borrow_date'),
        ),
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(check=models.Q(('actual_return_date__gte', django.db.models.expressions.F('borrow_date'))), name='actual_return_date_gte_borrow_date'),
        ),
    ]
