# Generated by Django 4.0.4 on 2024-06-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_initial'),
        ('borrowing', '0006_borrowing_expected_return_date_gte_borrow_date_and_more'),
    ]

    operations = [
    ]
