# Generated by Django 4.0.4 on 2024-06-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0006_borrowing_expected_return_date_gte_borrow_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowing',
            name='expected_return_date_gte_borrow_date',
        ),
        migrations.RemoveConstraint(
            model_name='borrowing',
            name='actual_return_date_gte_borrow_date',
        ),
    ]
